services:
  app:
    build: .
    container_name: note_of_beginning_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - 
  db:
    image: mysql:8.0
    container_name: note_of_beginning_db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  db_data:
